config/routes.rb
Catstagram::Application.routes.draw do
  root 'posts#index'

  devise_for :users

  resources :posts, only: [:index, :new, :create] do
    resources :meows, only: [:create, :destroy]
  end

end

app/models/meow.rb
class Meow < ActiveRecord::Base
  belongs_to :user,
    inverse_of: :meows

  belongs_to :post,
    inverse_of: :meows

  validates :user, presence: true
  validates :post, presence: true
  validates :post_id, uniqueness: { scope: :user_id }
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user,
    inverse_of: :posts

  has_many :meows,
    dependent: :destroy,
    inverse_of: :post

  validates :user, presence: true
  validates :image, presence: true
  validates :description, length: { maximum: 140 }

  mount_uploader :image, PostImageUploader

  def meow_from(user)
    meows.find_by(user_id: user.id)
  end

  def has_meow_from?(user)
    meows.find_by(user_id: user.id).present?
  end

  def self.by_recency
    order(created_at: :desc)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts,
    dependent: :destroy,
    inverse_of: :user

  has_many :meows,
    dependent: :destroy,
    inverse_of: :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/meows_controller.rb
class MeowsController < ApplicationController
  # /posts/:post_id/meows
  def create
    # Find the Post that we're "meowing" at
    post = Post.find(params[:post_id])
    # Build a Meow by the current user for the post
    meow = current_user.meows.build(post: post)

    respond_to do |format|
      if meow.save
        format.html { redirect_to :back, notice: "We heard your Meow!" }
        format.json { render json: meow }
      else
        format.html { redirect_to :back }
        format.json { render json: meow.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    current_user.meows.destroy(params[:id])

    respond_to do |format|
      # Respond the same way we were before if the request format is html
      format.html do
        flash[:notice] = "All evidence of your meowing has been destroyed!"
        redirect_to :back
      end

      # Respond with a "204 No Content" to signify that the request has been
      # fulfilled
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create]

  def index
    @posts = Post.by_recency
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to root_path, notice: "Post created successfully."
    else
      flash.now[:notice] = "There were some errors with your Post."
      render :new
    end
  end

  protected
  def post_params
    params.require(:post).permit(:image, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Catstagram</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
  <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
<% end %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<h1>Meow</h1>

<% @posts.each do |post| %>
  <div data-post-id="<%= post.id %>">
    <%= image_tag post.image.url %>
    <%= pluralize(post.meows.count, 'Meow') %>

    <% if user_signed_in? %>
      <% if post.has_meow_from?(current_user) %>
        <%= button_to "Remove Meow", post_meow_path(post, post.meow_from(current_user)),
          method: :delete,
          form: { data: { 'meow-button' => 'delete' } } %>
      <% else %>
        <%= button_to "Meow", post_meows_path(post),
          method: :post,
          form: { data: { 'meow-button' => 'create' } } %>
      <% end %>
    <% end %>

    <p><%= post.description %></p>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= simple_form_for @post do |f| %>
  <%= f.input :image, as: :file %>
  <%= f.input :description, as: :text %>
  <%= f.button :submit %>
<% end %>